version: '3.5'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: "on-failure:3"
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    networks:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

networks:
  nginx-proxy:
    name: nginx-proxy
