<?php

namespace Bdd2Bundle\Repository;

/**
 * HoldingAccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HoldingAccountRepository extends \Doctrine\ORM\EntityRepository
{
}
