<?php

namespace Bdd2Bundle\Repository;

/**
 * LinkedAccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkedAccountRepository extends \Doctrine\ORM\EntityRepository
{
}
