<?php

namespace Bdd2Bundle\Repository;

/**
 * UserTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserTagRepository extends \Doctrine\ORM\EntityRepository
{
}
